### ISSUE TITLE
Why use sequential consistent atomic?

### ISSUE THREAD

**Issue by MichaelSuen-thePointer** [colesbury/nogil-3.12#13]
-- This is not an official python repo so I put discussion here. --

I've read your blog. Using biased atomic ref counting is a genius idea. But in the code, I've noticed that you intentionally use sequential consistent atomic operations (seq_cst), in all of the atomic wrappers (std, gcc, msvc). Could you explain the reason behind the choice? 

https://github.com/colesbury/nogil-3.12/blob/nogil-3.12/Include/pyatomic_std.h#L21

**Comment by colesbury** [comment]
- It's always safe to use seq_cst in place of weaker memory orders
- It's simpler and less error prone, especially because we have to support MSVC, which does not support C11 atomic currently
- There's no significant performance impact on the platforms we care about

**Comment by MichaelSuen-thePointer** [comment]
> There's no significant performance impact on the platforms we care about

Ever tested on ARM platforms? From what I know, sequential consistent atomics are much heavier than acquire/release atomics in weak order CPUS.

**Comment by colesbury** [comment]
> From what I know, sequential consistent atomics are much heavier than acquire/release atomics in weak order CPUS.

No. On 64-bit ARM, you will see the same machine code generated for every (or nearly every) atomic operation we use for seq_cst vs. acq/rel.
